### ISSUE TITLE
[FOL] Archiv bere data z 2022 místo daného roku

### ISSUE THREAD

**Issue by rzehumat** [fykosak/webs#46]
Porovnejme ročníky: [2022](https://online.fyziklani.cz/2022/), [2021](https://online.fyziklani.cz/2021/), [2020](https://online.fyziklani.cz/2020/)
Furt to zobrazuje data "904 zúčastněných týmů z 59 zemí světa", což asi není pravda pro všechny roky.

**Comment by rzehumat** [comment]
Tipoval bych bug v `DefaultPresenter` nebo `MapComponent`

**Comment by cevro** [comment]
Rozbil to tento commit:

https://github.com/fykosak/webs/commit/cc1c4321e7bc0e7b70ace027a4144928b6f1a9fe

pretože https://github.com/fykosak/webs/blob/master/app/Models/GamePhaseCalculator.php#L155 berie najnovší event.

@vercah fixneš to?
