### ISSUE TITLE
Nečekané invertování vlajek v Dark Readeru

### ISSUE THREAD

**Issue by rzehumat** [fykosak/webs#66]
Při použití [Dark Readeru](https://darkreader.org/) některé vlajky nevhodně invertují barvy, zatímco jiné se zobrazí správně - beze změny. 

**Nevím, zda jde o problém v našem webu / ve frameworku / v Dark Readeru.**

Screenshot z [webu Fyziklání](https://fyziklani.cz/tymy) níže je pro ilustraci -- Česko se zobrazuje správně, Slovensko a Polsko ne. 
![fykos%dark%fail](https://github.com/fykosak/webs/assets/49885819/1a2778f6-823a-4bf7-92a0-8e59361017d4)

Špatně (invertovaně) se zobrazují
- Bulharsko
- Polsko
- Slovensko

Správně (bez invertování) se zobrazují
- Belgie
- Brazílie
- Česko
- Dánsko
- Estonsko
- Indie
- Itálie
- Maďarsko
- Rakousko
- Rumunsko
- Severní Makedonie
- Spojené Království
- Španělsko
- Turecko
- Vietnam

(Pardon, pokud je něco špatně seřazeno.)

Pozorováno v Brave 1.61.120 s Dark Readerem 4.9.76.

**Comment by cevro** [comment]
Smeroval by som toto issue sem:
https://github.com/darkreader/darkreader

**Comment by rzehumat** [comment]
Díky za doporučení.
